### ISSUE TITLE
problem with send command

### ISSUE THREAD

**Issue by ghost** [i8beef/HarmonyHub#2]
Hello
Many thanks for your library. I am familiarising with your software. Using your test client, I am sending commends to my hub. Most of them as accepted but sometimes I am getting the following exception error.  
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote hosts.
Can you explain the reason of this exception?
Command used to control hub:
client.SendCommand(“{"command":"ChannelUp","type":"IRCommand","deviceId":"22295412"}”);
client.SendCommand(“{"command":"ChannelDwon","type":"IRCommand","deviceId":"22295412"}”);   

Matthew

**Comment by i8beef** [comment]
Unfortunately I'm not sure. This library is still kind of unproven, as I'm just getting started with it, but that sounds like the hub is closing the connection prematurely. There's probably an opportunity for better error handling there.

Just to be clear, your example is just representative, and not the actual code you are using (as that wouldn't compile)?
1. How long is the connection open for? I.e., does this look like a timeout of some sort, or is it happening right after connection, which would indicate that the Harmony is upset and closing the connection early due to a malformed request?
2. Are you sure you are calling "client.Connect()"?

**Comment by ghost** [comment]
```
          I am sending you a snippet of my test.  I am sending message every second. Sometimes, the error occurs immediately or in 2/3 second. I am sorry for the client.send command prostration. I have removed backslashes in order to be more readable.
```

 try
                {
                    client.Connect();
                    Console.WriteLine("Devices ");
                    for (int i = 0; i < client.Config.Device.Count; i++)
                    {
                        Console.WriteLine(i+"         "+client.Config.Device[i].DeviceTypeDisplayName);
                        Console.WriteLine("           " + client.Config.Device[i].Label);
                    }

```
                var pvr = client.Config.Device.FirstOrDefault(x => x.Label == "Foxtel DVR");
                var channelAction = pvr.ControlGroup.FirstOrDefault(x => x.Name == "Channel");
                Console.WriteLine(channelAction.Name);

                Console.WriteLine(">>>> " + channelAction.Function.FirstOrDefault().Action);
                client.SendCommand(channelAction.Function.FirstOrDefault().Action);
                client.SendCommand("{ \"command\":\"ChannelUp\",\"type\":\"IRCommand\",\"deviceId\":\"22295412\"}");
                System.Threading.Thread.Sleep(1000);
                client.SendCommand("{ \"command\":\"ChannelDwon\",\"type\":\"IRCommand\",\"deviceId\":\"22295412\"}");
                System.Threading.Thread.Sleep(1000);
                client.SendCommand("{ \"command\":\"ChannelUp\",\"type\":\"IRCommand\",\"deviceId\":\"22295412\"}");
                System.Threading.Thread.Sleep(1000);
                client.SendCommand("{ \"command\":\"ChannelDwon\",\"type\":\"IRCommand\",\"deviceId\":\"22295412\"}");
                System.Threading.Thread.Sleep(1000);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            Console.WriteLine("Done");
            Console.ReadLine();
```

**Comment by i8beef** [comment]
Well, your problem is rather easy to fix and is due to a bug with handling ping responses from the Harmony... but it introduces a different issue with the way I handle (or attempt to handle) reestablishing the connection in the case of a ping failure. I had a TODO there already to establish if how I'm handling a response failure there is correct or not... apparently it's not.

I'm removing that logic for now and am just raising an error event. This kind of punts the problem of handling streams closing to the caller for now...
