### ISSUE TITLE
Parsing error of response from HUB

### ISSUE THREAD

**Issue by WoodsterDK** [i8beef/HarmonyHub#4]
Hi There,

Interesting project - and very usefull, I plan to make a HubToMQTT service.

I get : Error converting value \"191532\" to type 'HarmonyHub.Config.SequenceConfigElement'. Path 'activity[0].sequences[0]', line 1, position 162."}

It seems there is a part of the file with elements 'sequence' that fails.
Any idea?

**Comment by i8beef** [comment]
If that's what you're looking to do, you should checkout my other repo, HomeAutio.Mqtt.HarmonyHub, just saying. You can at least get some inspiration from it I guess.

As for your issue, it's been a while since I've looked at this structure so I don't remember what that element does... I know it's always empty on my GetConfig on my local stuff, so I'm unsure what triggers it, but this is almost certainly a bug... I just don't know how to trigger it.

There are two areas of the config object (that I can think of) that are a bit of a mystery: sequences and rules. I think that the type for this collection is wrong, and from the looks of the error, should probably be either a List<int> or List<string>, and point to a SequenceConfigElement in the config.Sequences collection instead...

Are you in a position to pull down the repo and run the test client? If so, depending on how deep you want to go, you could try changing the file "ActivityConfigElement" to make Sequences an IList<int> or IList<string> and see if that gets you over the hump... and then make a pull request back to fix this bug :-). Or just tell me which worked and I'll change it.

If you don't feel like doing that, if you can stick a break point in Client.cs on line 114 and dump the relevant section here from result.FirstChild.InnerText (looks like the first "activity" object's "sequences" node) I'm sure I can get something in place for you.

**Comment by WoodsterDK** [comment]
Hi, thanks for quick answer.
HomeAutio.Mqtt.HarmonyHub looks quite as what I had in mind.☺
The sequence part is not empty in my config. It seems to be some Logitech virtual stuff.
I can give it shot later today, or post the content, if I cant figure it out.
Will get back, have a nice day.

**Comment by WoodsterDK** [comment]
Used "http://jsonviewer.stack.hu/" to visualize the "result.FirstChild.InnerText)" and could see, that two thing had to be changed to be able to parse the json string:

ActivityConfigElement:
        [DataMember(Name = "sequences")]
        public IList<string> Sequences { get; set; }

And:
SequenceConfigElement:
    [DataContract]
    public class SequenceConfigElement
    {
        [DataMember(Name = "id")]
        public string Id { get; set; }

        [DataMember(Name = "name")]
        public string Name { get; set; }
    }

Currently I'm away from my hardware, so cannot test - can just tell that the string now generates a HarmonyConfig

**Comment by i8beef** [comment]
Changed and pushed, should be a new version up momentarily.

**Comment by WoodsterDK** [comment]
Just to verify - it reads out the config now.
