### ISSUE TITLE
V 3.0.0.1 not compatible to any .net framework?

### ISSUE THREAD

**Issue by WueBumbum** [i8beef/HarmonyHub#8]
Hello,

if I try to install the V 3.0.0.1 I always get a message like:

Could not install package 'HarmonyHub 3.0.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

No matter which framework I choose for my project.

best regards,
Bumbum

**Comment by i8beef** [comment]
This major version is now a .NET Standard 2.0 library. That seemed like the first actual implementation that was really prime time ready, and I was waiting on it to solidify and then moved all my libraries to it.

Your issue is that 4.5.2 is NOT .NET Standard 2.0 compatible. That's going to be 4.6.1 (https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

Conceivably, this library could actually use a lower .NET Standard version, it just wasn't my intention to support anything below 2.0 because that seems to have been the point where the standard had solidified enough to be usable.

**Comment by WueBumbum** [comment]
Hello i8beef,

I wrote no matter which framework I choose for my project. Of course I have tried other frameworks loke 2.0 and 4.6.1 or 4.6.2. or 3.0, 3.5. 4, 4.5.... None of them is working.

best regards,
Bumbum

**Comment by i8beef** [comment]
I just confirmed with a new 4.6.1 project that it DOES in fact work. Do you by chance not have the .NET Core 2.0 SDK installed? That Microsoft page seems to indicate that you might need that to use .NET Standard libs in the main framework.

**Comment by WueBumbum** [comment]
I just downloaded the SDK and installed it. Unfortunately it solved not my problem. I also checked for updates, nothing here. All is up to date on my system.

I also tried creating new projects with different framework versions. None of them will install the 3.0.0.1. With the 2.0.0.39 everything is fine.

**Comment by i8beef** [comment]
Something is off on your setup then. Sounds like you can't consume .NET Standard 2.0 libs at all. I know it works just fine on VS 2017 with the Core 2.0 SDK installed. Maybe you are on 2015, or your NuGet.exe is out of date?

**Comment by WueBumbum** [comment]
Hello,

I just want to give a short feedback. I have used Visual Studio 2015. After I have installed 2017 it is working.,
Thank you for your support!

best regards,
Bumbum
